# Generated by Django 5.0.4 on 2024-05-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_doa', models.CharField(max_length=100)),
                ('teks_doa_latin', models.TextField()),
                ('teks_doa_arab', models.TextField()),
                ('arti_doa', models.TextField()),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.kategori')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.penulisdoa')),
            ],
        ),
    ]
